  [[redirects]]
  from = "/login"
  to = "http://localhost/v1/account/sessions/email/:splat"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"